### ISSUE TITLE
Missing `job name` in the `.github\workflows\binaries.yml` file

### ISSUE THREAD

**Issue by Sai-Suraj-27** [unifyai/ivy#26856]
Missing job name for the `.github\workflows\binaries.yml` Workflow. The workflow is missing a name field, which is important as it is good to have a meaningful and descriptive name for the workflow.

https://github.com/unifyai/ivy/blob/8608b7f9cda83f78b3409eaa33a47701c76bfa21/.github/workflows/binaries.yml#L4
I'm not sure but a name like `release_binaries:` or `tag_binary_release:` could be added.

```YAML
jobs:
  release_binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Binaries
        uses: actions/checkout@v2
        with:
          repository: unifyai/binaries
          path: binaries
          persist-credentials: false

      - name: Add Tag to Binaries
        run: |
          cd binaries
          git tag ${{ github.ref_name }}
          git push origin ${{ github.ref_name }}
```
